const result = {
  "total_count": 36276,
  "incomplete_results": false,
  "items": [
    {
      "id": 106017343,
      "node_id": "MDEwOlJlcG9zaXRvcnkxMDYwMTczNDM=",
      "name": "tailwindcss",
      "full_name": "tailwindlabs/tailwindcss",
      "private": false,
      "owner": {
        "login": "tailwindlabs",
        "id": 67109815,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjY3MTA5ODE1",
        "avatar_url": "https://avatars.githubusercontent.com/u/67109815?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tailwindlabs",
        "html_url": "https://github.com/tailwindlabs",
        "followers_url": "https://api.github.com/users/tailwindlabs/followers",
        "following_url": "https://api.github.com/users/tailwindlabs/following{/other_user}",
        "gists_url": "https://api.github.com/users/tailwindlabs/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tailwindlabs/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tailwindlabs/subscriptions",
        "organizations_url": "https://api.github.com/users/tailwindlabs/orgs",
        "repos_url": "https://api.github.com/users/tailwindlabs/repos",
        "events_url": "https://api.github.com/users/tailwindlabs/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tailwindlabs/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "html_url": "https://github.com/tailwindlabs/tailwindcss",
      "description": "A utility-first CSS framework for rapid UI development.",
      "fork": false,
      "url": "https://api.github.com/repos/tailwindlabs/tailwindcss",
      "forks_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/forks",
      "keys_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/teams",
      "hooks_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/hooks",
      "issue_events_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/issues/events{/number}",
      "events_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/events",
      "assignees_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/assignees{/user}",
      "branches_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/branches{/branch}",
      "tags_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/tags",
      "blobs_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/languages",
      "stargazers_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/stargazers",
      "contributors_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/contributors",
      "subscribers_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/subscribers",
      "subscription_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/subscription",
      "commits_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/contents/{+path}",
      "compare_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/merges",
      "archive_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/downloads",
      "issues_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/issues{/number}",
      "pulls_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/labels{/name}",
      "releases_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/releases{/id}",
      "deployments_url": "https://api.github.com/repos/tailwindlabs/tailwindcss/deployments",
      "created_at": "2017-10-06T14:59:14Z",
      "updated_at": "2021-12-19T07:29:11Z",
      "pushed_at": "2021-12-18T23:41:10Z",
      "git_url": "git://github.com/tailwindlabs/tailwindcss.git",
      "ssh_url": "git@github.com:tailwindlabs/tailwindcss.git",
      "clone_url": "https://github.com/tailwindlabs/tailwindcss.git",
      "svn_url": "https://github.com/tailwindlabs/tailwindcss",
      "homepage": "https://tailwindcss.com/",
      "size": 60611,
      "stargazers_count": 50890,
      "watchers_count": 50890,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": false,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": false,
      "forks_count": 2410,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 73,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [
        "css",
        "css-framework",
        "functional-css",
        "postcss",
        "responsive",
        "tailwindcss",
        "utility-classes"
      ],
      "visibility": "public",
      "forks": 2410,
      "open_issues": 73,
      "watchers": 50890,
      "default_branch": "master",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "score": 1.0
    },
    {
      "id": 295992065,
      "node_id": "MDEwOlJlcG9zaXRvcnkyOTU5OTIwNjU=",
      "name": "headlessui",
      "full_name": "tailwindlabs/headlessui",
      "private": false,
      "owner": {
        "login": "tailwindlabs",
        "id": 67109815,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjY3MTA5ODE1",
        "avatar_url": "https://avatars.githubusercontent.com/u/67109815?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tailwindlabs",
        "html_url": "https://github.com/tailwindlabs",
        "followers_url": "https://api.github.com/users/tailwindlabs/followers",
        "following_url": "https://api.github.com/users/tailwindlabs/following{/other_user}",
        "gists_url": "https://api.github.com/users/tailwindlabs/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tailwindlabs/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tailwindlabs/subscriptions",
        "organizations_url": "https://api.github.com/users/tailwindlabs/orgs",
        "repos_url": "https://api.github.com/users/tailwindlabs/repos",
        "events_url": "https://api.github.com/users/tailwindlabs/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tailwindlabs/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "html_url": "https://github.com/tailwindlabs/headlessui",
      "description": "Completely unstyled, fully accessible UI components, designed to integrate beautifully with Tailwind CSS.",
      "fork": false,
      "url": "https://api.github.com/repos/tailwindlabs/headlessui",
      "forks_url": "https://api.github.com/repos/tailwindlabs/headlessui/forks",
      "keys_url": "https://api.github.com/repos/tailwindlabs/headlessui/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/tailwindlabs/headlessui/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/tailwindlabs/headlessui/teams",
      "hooks_url": "https://api.github.com/repos/tailwindlabs/headlessui/hooks",
      "issue_events_url": "https://api.github.com/repos/tailwindlabs/headlessui/issues/events{/number}",
      "events_url": "https://api.github.com/repos/tailwindlabs/headlessui/events",
      "assignees_url": "https://api.github.com/repos/tailwindlabs/headlessui/assignees{/user}",
      "branches_url": "https://api.github.com/repos/tailwindlabs/headlessui/branches{/branch}",
      "tags_url": "https://api.github.com/repos/tailwindlabs/headlessui/tags",
      "blobs_url": "https://api.github.com/repos/tailwindlabs/headlessui/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/tailwindlabs/headlessui/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/tailwindlabs/headlessui/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/tailwindlabs/headlessui/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/tailwindlabs/headlessui/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/tailwindlabs/headlessui/languages",
      "stargazers_url": "https://api.github.com/repos/tailwindlabs/headlessui/stargazers",
      "contributors_url": "https://api.github.com/repos/tailwindlabs/headlessui/contributors",
      "subscribers_url": "https://api.github.com/repos/tailwindlabs/headlessui/subscribers",
      "subscription_url": "https://api.github.com/repos/tailwindlabs/headlessui/subscription",
      "commits_url": "https://api.github.com/repos/tailwindlabs/headlessui/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/tailwindlabs/headlessui/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/tailwindlabs/headlessui/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/tailwindlabs/headlessui/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/tailwindlabs/headlessui/contents/{+path}",
      "compare_url": "https://api.github.com/repos/tailwindlabs/headlessui/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/tailwindlabs/headlessui/merges",
      "archive_url": "https://api.github.com/repos/tailwindlabs/headlessui/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/tailwindlabs/headlessui/downloads",
      "issues_url": "https://api.github.com/repos/tailwindlabs/headlessui/issues{/number}",
      "pulls_url": "https://api.github.com/repos/tailwindlabs/headlessui/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/tailwindlabs/headlessui/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/tailwindlabs/headlessui/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/tailwindlabs/headlessui/labels{/name}",
      "releases_url": "https://api.github.com/repos/tailwindlabs/headlessui/releases{/id}",
      "deployments_url": "https://api.github.com/repos/tailwindlabs/headlessui/deployments",
      "created_at": "2020-09-16T09:53:09Z",
      "updated_at": "2021-12-19T05:47:11Z",
      "pushed_at": "2021-12-18T23:41:42Z",
      "git_url": "git://github.com/tailwindlabs/headlessui.git",
      "ssh_url": "git@github.com:tailwindlabs/headlessui.git",
      "clone_url": "https://github.com/tailwindlabs/headlessui.git",
      "svn_url": "https://github.com/tailwindlabs/headlessui",
      "homepage": "https://headlessui.dev",
      "size": 1174,
      "stargazers_count": 12195,
      "watchers_count": 12195,
      "language": "TypeScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": false,
      "forks_count": 430,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 89,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [

      ],
      "visibility": "public",
      "forks": 430,
      "open_issues": 89,
      "watchers": 12195,
      "default_branch": "main",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "score": 1.0
    },
    {
      "id": 109994573,
      "node_id": "MDEwOlJlcG9zaXRvcnkxMDk5OTQ1NzM=",
      "name": "awesome-tailwindcss",
      "full_name": "aniftyco/awesome-tailwindcss",
      "private": false,
      "owner": {
        "login": "aniftyco",
        "id": 18599486,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjE4NTk5NDg2",
        "avatar_url": "https://avatars.githubusercontent.com/u/18599486?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/aniftyco",
        "html_url": "https://github.com/aniftyco",
        "followers_url": "https://api.github.com/users/aniftyco/followers",
        "following_url": "https://api.github.com/users/aniftyco/following{/other_user}",
        "gists_url": "https://api.github.com/users/aniftyco/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/aniftyco/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/aniftyco/subscriptions",
        "organizations_url": "https://api.github.com/users/aniftyco/orgs",
        "repos_url": "https://api.github.com/users/aniftyco/repos",
        "events_url": "https://api.github.com/users/aniftyco/events{/privacy}",
        "received_events_url": "https://api.github.com/users/aniftyco/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "html_url": "https://github.com/aniftyco/awesome-tailwindcss",
      "description": "😎 Awesome things related to Tailwind CSS",
      "fork": false,
      "url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss",
      "forks_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/forks",
      "keys_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/teams",
      "hooks_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/hooks",
      "issue_events_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/issues/events{/number}",
      "events_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/events",
      "assignees_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/assignees{/user}",
      "branches_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/branches{/branch}",
      "tags_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/tags",
      "blobs_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/languages",
      "stargazers_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/stargazers",
      "contributors_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/contributors",
      "subscribers_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/subscribers",
      "subscription_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/subscription",
      "commits_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/contents/{+path}",
      "compare_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/merges",
      "archive_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/downloads",
      "issues_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/issues{/number}",
      "pulls_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/labels{/name}",
      "releases_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/releases{/id}",
      "deployments_url": "https://api.github.com/repos/aniftyco/awesome-tailwindcss/deployments",
      "created_at": "2017-11-08T15:35:50Z",
      "updated_at": "2021-12-19T04:55:50Z",
      "pushed_at": "2021-12-18T21:14:25Z",
      "git_url": "git://github.com/aniftyco/awesome-tailwindcss.git",
      "ssh_url": "git@github.com:aniftyco/awesome-tailwindcss.git",
      "clone_url": "https://github.com/aniftyco/awesome-tailwindcss.git",
      "svn_url": "https://github.com/aniftyco/awesome-tailwindcss",
      "homepage": "https://tailwindcss.com",
      "size": 703,
      "stargazers_count": 7791,
      "watchers_count": 7791,
      "language": null,
      "has_issues": false,
      "has_projects": false,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": false,
      "forks_count": 624,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": {
        "key": "cc0-1.0",
        "name": "Creative Commons Zero v1.0 Universal",
        "spdx_id": "CC0-1.0",
        "url": "https://api.github.com/licenses/cc0-1.0",
        "node_id": "MDc6TGljZW5zZTY="
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [
        "apps",
        "awesome",
        "awesome-list",
        "css",
        "postcss",
        "resources",
        "tailwind",
        "tailwindcss",
        "websites"
      ],
      "visibility": "public",
      "forks": 624,
      "open_issues": 0,
      "watchers": 7791,
      "default_branch": "master",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "score": 1.0
    },
    {
      "id": 316836816,
      "node_id": "MDEwOlJlcG9zaXRvcnkzMTY4MzY4MTY=",
      "name": "daisyui",
      "full_name": "saadeghi/daisyui",
      "private": false,
      "owner": {
        "login": "saadeghi",
        "id": 7342023,
        "node_id": "MDQ6VXNlcjczNDIwMjM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7342023?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/saadeghi",
        "html_url": "https://github.com/saadeghi",
        "followers_url": "https://api.github.com/users/saadeghi/followers",
        "following_url": "https://api.github.com/users/saadeghi/following{/other_user}",
        "gists_url": "https://api.github.com/users/saadeghi/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/saadeghi/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/saadeghi/subscriptions",
        "organizations_url": "https://api.github.com/users/saadeghi/orgs",
        "repos_url": "https://api.github.com/users/saadeghi/repos",
        "events_url": "https://api.github.com/users/saadeghi/events{/privacy}",
        "received_events_url": "https://api.github.com/users/saadeghi/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/saadeghi/daisyui",
      "description": "⭐️ ⭐️ ⭐️ ⭐️ ⭐️  Tailwind Components",
      "fork": false,
      "url": "https://api.github.com/repos/saadeghi/daisyui",
      "forks_url": "https://api.github.com/repos/saadeghi/daisyui/forks",
      "keys_url": "https://api.github.com/repos/saadeghi/daisyui/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/saadeghi/daisyui/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/saadeghi/daisyui/teams",
      "hooks_url": "https://api.github.com/repos/saadeghi/daisyui/hooks",
      "issue_events_url": "https://api.github.com/repos/saadeghi/daisyui/issues/events{/number}",
      "events_url": "https://api.github.com/repos/saadeghi/daisyui/events",
      "assignees_url": "https://api.github.com/repos/saadeghi/daisyui/assignees{/user}",
      "branches_url": "https://api.github.com/repos/saadeghi/daisyui/branches{/branch}",
      "tags_url": "https://api.github.com/repos/saadeghi/daisyui/tags",
      "blobs_url": "https://api.github.com/repos/saadeghi/daisyui/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/saadeghi/daisyui/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/saadeghi/daisyui/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/saadeghi/daisyui/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/saadeghi/daisyui/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/saadeghi/daisyui/languages",
      "stargazers_url": "https://api.github.com/repos/saadeghi/daisyui/stargazers",
      "contributors_url": "https://api.github.com/repos/saadeghi/daisyui/contributors",
      "subscribers_url": "https://api.github.com/repos/saadeghi/daisyui/subscribers",
      "subscription_url": "https://api.github.com/repos/saadeghi/daisyui/subscription",
      "commits_url": "https://api.github.com/repos/saadeghi/daisyui/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/saadeghi/daisyui/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/saadeghi/daisyui/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/saadeghi/daisyui/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/saadeghi/daisyui/contents/{+path}",
      "compare_url": "https://api.github.com/repos/saadeghi/daisyui/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/saadeghi/daisyui/merges",
      "archive_url": "https://api.github.com/repos/saadeghi/daisyui/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/saadeghi/daisyui/downloads",
      "issues_url": "https://api.github.com/repos/saadeghi/daisyui/issues{/number}",
      "pulls_url": "https://api.github.com/repos/saadeghi/daisyui/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/saadeghi/daisyui/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/saadeghi/daisyui/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/saadeghi/daisyui/labels{/name}",
      "releases_url": "https://api.github.com/repos/saadeghi/daisyui/releases{/id}",
      "deployments_url": "https://api.github.com/repos/saadeghi/daisyui/deployments",
      "created_at": "2020-11-28T22:57:27Z",
      "updated_at": "2021-12-19T04:55:32Z",
      "pushed_at": "2021-12-16T14:45:51Z",
      "git_url": "git://github.com/saadeghi/daisyui.git",
      "ssh_url": "git@github.com:saadeghi/daisyui.git",
      "clone_url": "https://github.com/saadeghi/daisyui.git",
      "svn_url": "https://github.com/saadeghi/daisyui",
      "homepage": "https://daisyui.com",
      "size": 16860,
      "stargazers_count": 6772,
      "watchers_count": 6772,
      "language": "Vue",
      "has_issues": true,
      "has_projects": false,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": true,
      "forks_count": 252,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 30,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [
        "component",
        "component-library",
        "components",
        "css",
        "css-components",
        "css-framework",
        "design-pattern",
        "design-system",
        "design-systems",
        "postcss",
        "tailwind",
        "tailwind-css",
        "tailwindcss",
        "ui-components",
        "ui-design",
        "ui-framework",
        "ui-kit",
        "ui-library",
        "ui-pattern"
      ],
      "visibility": "public",
      "forks": 252,
      "open_issues": 30,
      "watchers": 6772,
      "default_branch": "master",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "score": 1.0
    },
    {
      "id": 263993730,
      "node_id": "MDEwOlJlcG9zaXRvcnkyNjM5OTM3MzA=",
      "name": "tailblocks",
      "full_name": "mertJF/tailblocks",
      "private": false,
      "owner": {
        "login": "mertJF",
        "id": 34642289,
        "node_id": "MDQ6VXNlcjM0NjQyMjg5",
        "avatar_url": "https://avatars.githubusercontent.com/u/34642289?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mertJF",
        "html_url": "https://github.com/mertJF",
        "followers_url": "https://api.github.com/users/mertJF/followers",
        "following_url": "https://api.github.com/users/mertJF/following{/other_user}",
        "gists_url": "https://api.github.com/users/mertJF/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mertJF/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mertJF/subscriptions",
        "organizations_url": "https://api.github.com/users/mertJF/orgs",
        "repos_url": "https://api.github.com/users/mertJF/repos",
        "events_url": "https://api.github.com/users/mertJF/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mertJF/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/mertJF/tailblocks",
      "description": "Ready-to-use Tailwind CSS blocks.",
      "fork": false,
      "url": "https://api.github.com/repos/mertJF/tailblocks",
      "forks_url": "https://api.github.com/repos/mertJF/tailblocks/forks",
      "keys_url": "https://api.github.com/repos/mertJF/tailblocks/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/mertJF/tailblocks/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/mertJF/tailblocks/teams",
      "hooks_url": "https://api.github.com/repos/mertJF/tailblocks/hooks",
      "issue_events_url": "https://api.github.com/repos/mertJF/tailblocks/issues/events{/number}",
      "events_url": "https://api.github.com/repos/mertJF/tailblocks/events",
      "assignees_url": "https://api.github.com/repos/mertJF/tailblocks/assignees{/user}",
      "branches_url": "https://api.github.com/repos/mertJF/tailblocks/branches{/branch}",
      "tags_url": "https://api.github.com/repos/mertJF/tailblocks/tags",
      "blobs_url": "https://api.github.com/repos/mertJF/tailblocks/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/mertJF/tailblocks/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/mertJF/tailblocks/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/mertJF/tailblocks/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/mertJF/tailblocks/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/mertJF/tailblocks/languages",
      "stargazers_url": "https://api.github.com/repos/mertJF/tailblocks/stargazers",
      "contributors_url": "https://api.github.com/repos/mertJF/tailblocks/contributors",
      "subscribers_url": "https://api.github.com/repos/mertJF/tailblocks/subscribers",
      "subscription_url": "https://api.github.com/repos/mertJF/tailblocks/subscription",
      "commits_url": "https://api.github.com/repos/mertJF/tailblocks/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/mertJF/tailblocks/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/mertJF/tailblocks/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/mertJF/tailblocks/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/mertJF/tailblocks/contents/{+path}",
      "compare_url": "https://api.github.com/repos/mertJF/tailblocks/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/mertJF/tailblocks/merges",
      "archive_url": "https://api.github.com/repos/mertJF/tailblocks/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/mertJF/tailblocks/downloads",
      "issues_url": "https://api.github.com/repos/mertJF/tailblocks/issues{/number}",
      "pulls_url": "https://api.github.com/repos/mertJF/tailblocks/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/mertJF/tailblocks/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/mertJF/tailblocks/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/mertJF/tailblocks/labels{/name}",
      "releases_url": "https://api.github.com/repos/mertJF/tailblocks/releases{/id}",
      "deployments_url": "https://api.github.com/repos/mertJF/tailblocks/deployments",
      "created_at": "2020-05-14T18:26:36Z",
      "updated_at": "2021-12-19T05:45:00Z",
      "pushed_at": "2021-08-23T07:44:52Z",
      "git_url": "git://github.com/mertJF/tailblocks.git",
      "ssh_url": "git@github.com:mertJF/tailblocks.git",
      "clone_url": "https://github.com/mertJF/tailblocks.git",
      "svn_url": "https://github.com/mertJF/tailblocks",
      "homepage": "https://tailblocks.cc",
      "size": 26393,
      "stargazers_count": 6660,
      "watchers_count": 6660,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": true,
      "forks_count": 601,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 23,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [
        "css",
        "tailblocks",
        "tailwind",
        "ui-components"
      ],
      "visibility": "public",
      "forks": 601,
      "open_issues": 23,
      "watchers": 6660,
      "default_branch": "master",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "score": 1.0
    },
    {
      "id": 241534790,
      "node_id": "MDEwOlJlcG9zaXRvcnkyNDE1MzQ3OTA=",
      "name": "twin.macro",
      "full_name": "ben-rogerson/twin.macro",
      "private": false,
      "owner": {
        "login": "ben-rogerson",
        "id": 21288568,
        "node_id": "MDQ6VXNlcjIxMjg4NTY4",
        "avatar_url": "https://avatars.githubusercontent.com/u/21288568?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ben-rogerson",
        "html_url": "https://github.com/ben-rogerson",
        "followers_url": "https://api.github.com/users/ben-rogerson/followers",
        "following_url": "https://api.github.com/users/ben-rogerson/following{/other_user}",
        "gists_url": "https://api.github.com/users/ben-rogerson/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ben-rogerson/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ben-rogerson/subscriptions",
        "organizations_url": "https://api.github.com/users/ben-rogerson/orgs",
        "repos_url": "https://api.github.com/users/ben-rogerson/repos",
        "events_url": "https://api.github.com/users/ben-rogerson/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ben-rogerson/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/ben-rogerson/twin.macro",
      "description": "🦹‍♂️ Twin blends the magic of Tailwind with the flexibility of css-in-js (emotion, styled-components, stitches and goober) at build time.",
      "fork": false,
      "url": "https://api.github.com/repos/ben-rogerson/twin.macro",
      "forks_url": "https://api.github.com/repos/ben-rogerson/twin.macro/forks",
      "keys_url": "https://api.github.com/repos/ben-rogerson/twin.macro/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/ben-rogerson/twin.macro/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/ben-rogerson/twin.macro/teams",
      "hooks_url": "https://api.github.com/repos/ben-rogerson/twin.macro/hooks",
      "issue_events_url": "https://api.github.com/repos/ben-rogerson/twin.macro/issues/events{/number}",
      "events_url": "https://api.github.com/repos/ben-rogerson/twin.macro/events",
      "assignees_url": "https://api.github.com/repos/ben-rogerson/twin.macro/assignees{/user}",
      "branches_url": "https://api.github.com/repos/ben-rogerson/twin.macro/branches{/branch}",
      "tags_url": "https://api.github.com/repos/ben-rogerson/twin.macro/tags",
      "blobs_url": "https://api.github.com/repos/ben-rogerson/twin.macro/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/ben-rogerson/twin.macro/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/ben-rogerson/twin.macro/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/ben-rogerson/twin.macro/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/ben-rogerson/twin.macro/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/ben-rogerson/twin.macro/languages",
      "stargazers_url": "https://api.github.com/repos/ben-rogerson/twin.macro/stargazers",
      "contributors_url": "https://api.github.com/repos/ben-rogerson/twin.macro/contributors",
      "subscribers_url": "https://api.github.com/repos/ben-rogerson/twin.macro/subscribers",
      "subscription_url": "https://api.github.com/repos/ben-rogerson/twin.macro/subscription",
      "commits_url": "https://api.github.com/repos/ben-rogerson/twin.macro/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/ben-rogerson/twin.macro/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/ben-rogerson/twin.macro/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/ben-rogerson/twin.macro/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/ben-rogerson/twin.macro/contents/{+path}",
      "compare_url": "https://api.github.com/repos/ben-rogerson/twin.macro/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/ben-rogerson/twin.macro/merges",
      "archive_url": "https://api.github.com/repos/ben-rogerson/twin.macro/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/ben-rogerson/twin.macro/downloads",
      "issues_url": "https://api.github.com/repos/ben-rogerson/twin.macro/issues{/number}",
      "pulls_url": "https://api.github.com/repos/ben-rogerson/twin.macro/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/ben-rogerson/twin.macro/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/ben-rogerson/twin.macro/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/ben-rogerson/twin.macro/labels{/name}",
      "releases_url": "https://api.github.com/repos/ben-rogerson/twin.macro/releases{/id}",
      "deployments_url": "https://api.github.com/repos/ben-rogerson/twin.macro/deployments",
      "created_at": "2020-02-19T04:45:25Z",
      "updated_at": "2021-12-19T04:51:58Z",
      "pushed_at": "2021-12-11T12:07:26Z",
      "git_url": "git://github.com/ben-rogerson/twin.macro.git",
      "ssh_url": "git@github.com:ben-rogerson/twin.macro.git",
      "clone_url": "https://github.com/ben-rogerson/twin.macro.git",
      "svn_url": "https://github.com/ben-rogerson/twin.macro",
      "homepage": "",
      "size": 5743,
      "stargazers_count": 5137,
      "watchers_count": 5137,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": false,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": false,
      "forks_count": 117,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 14,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [
        "babel",
        "babel-macro",
        "css-in-js",
        "emotion",
        "emotionjs",
        "goober",
        "react",
        "reactjs",
        "stitches",
        "styled-components",
        "styling-css-in-js",
        "styling-react",
        "tailwind",
        "tailwind-css",
        "tailwind-in-js",
        "tailwindcss",
        "twin"
      ],
      "visibility": "public",
      "forks": 117,
      "open_issues": 14,
      "watchers": 5137,
      "default_branch": "master",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "score": 1.0
    },
    {
      "id": 229293658,
      "node_id": "MDEwOlJlcG9zaXRvcnkyMjkyOTM2NTg=",
      "name": "tailwind-starter-kit",
      "full_name": "creativetimofficial/tailwind-starter-kit",
      "private": false,
      "owner": {
        "login": "creativetimofficial",
        "id": 20172349,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjIwMTcyMzQ5",
        "avatar_url": "https://avatars.githubusercontent.com/u/20172349?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/creativetimofficial",
        "html_url": "https://github.com/creativetimofficial",
        "followers_url": "https://api.github.com/users/creativetimofficial/followers",
        "following_url": "https://api.github.com/users/creativetimofficial/following{/other_user}",
        "gists_url": "https://api.github.com/users/creativetimofficial/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/creativetimofficial/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/creativetimofficial/subscriptions",
        "organizations_url": "https://api.github.com/users/creativetimofficial/orgs",
        "repos_url": "https://api.github.com/users/creativetimofficial/repos",
        "events_url": "https://api.github.com/users/creativetimofficial/events{/privacy}",
        "received_events_url": "https://api.github.com/users/creativetimofficial/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "html_url": "https://github.com/creativetimofficial/tailwind-starter-kit",
      "description": "Tailwind Starter Kit a beautiful extension for TailwindCSS, Free and Open Source",
      "fork": false,
      "url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit",
      "forks_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/forks",
      "keys_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/teams",
      "hooks_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/hooks",
      "issue_events_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/issues/events{/number}",
      "events_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/events",
      "assignees_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/assignees{/user}",
      "branches_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/branches{/branch}",
      "tags_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/tags",
      "blobs_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/languages",
      "stargazers_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/stargazers",
      "contributors_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/contributors",
      "subscribers_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/subscribers",
      "subscription_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/subscription",
      "commits_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/contents/{+path}",
      "compare_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/merges",
      "archive_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/downloads",
      "issues_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/issues{/number}",
      "pulls_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/labels{/name}",
      "releases_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/releases{/id}",
      "deployments_url": "https://api.github.com/repos/creativetimofficial/tailwind-starter-kit/deployments",
      "created_at": "2019-12-20T15:56:31Z",
      "updated_at": "2021-12-19T00:19:01Z",
      "pushed_at": "2021-10-23T13:46:27Z",
      "git_url": "git://github.com/creativetimofficial/tailwind-starter-kit.git",
      "ssh_url": "git@github.com:creativetimofficial/tailwind-starter-kit.git",
      "clone_url": "https://github.com/creativetimofficial/tailwind-starter-kit.git",
      "svn_url": "https://github.com/creativetimofficial/tailwind-starter-kit",
      "homepage": "https://www.creative-tim.com/learning-lab/tailwind-starter-kit#/presentation",
      "size": 34041,
      "stargazers_count": 4435,
      "watchers_count": 4435,
      "language": "CSS",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 650,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 15,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [
        "angular-landing-page",
        "dashboard",
        "dynamic-components",
        "kits",
        "tailwind-admin",
        "tailwind-css",
        "tailwind-css-template",
        "tailwind-react",
        "tailwind-starter-kit",
        "tailwind-vue",
        "tailwindcss",
        "tailwindcss-extension",
        "tailwindcss-starter-kit",
        "tailwindcss-starter-project"
      ],
      "visibility": "public",
      "forks": 650,
      "open_issues": 15,
      "watchers": 4435,
      "default_branch": "main",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "score": 1.0
    },
    {
      "id": 184605387,
      "node_id": "MDEwOlJlcG9zaXRvcnkxODQ2MDUzODc=",
      "name": "material-kit-react",
      "full_name": "devias-io/material-kit-react",
      "private": false,
      "owner": {
        "login": "devias-io",
        "id": 49873471,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ5ODczNDcx",
        "avatar_url": "https://avatars.githubusercontent.com/u/49873471?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/devias-io",
        "html_url": "https://github.com/devias-io",
        "followers_url": "https://api.github.com/users/devias-io/followers",
        "following_url": "https://api.github.com/users/devias-io/following{/other_user}",
        "gists_url": "https://api.github.com/users/devias-io/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/devias-io/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/devias-io/subscriptions",
        "organizations_url": "https://api.github.com/users/devias-io/orgs",
        "repos_url": "https://api.github.com/users/devias-io/repos",
        "events_url": "https://api.github.com/users/devias-io/events{/privacy}",
        "received_events_url": "https://api.github.com/users/devias-io/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "html_url": "https://github.com/devias-io/material-kit-react",
      "description": "React Dashboard made with Material UI’s components. Our pro template contains features like TypeScript version, authentication system with Firebase and Auth0 plus many other ",
      "fork": false,
      "url": "https://api.github.com/repos/devias-io/material-kit-react",
      "forks_url": "https://api.github.com/repos/devias-io/material-kit-react/forks",
      "keys_url": "https://api.github.com/repos/devias-io/material-kit-react/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/devias-io/material-kit-react/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/devias-io/material-kit-react/teams",
      "hooks_url": "https://api.github.com/repos/devias-io/material-kit-react/hooks",
      "issue_events_url": "https://api.github.com/repos/devias-io/material-kit-react/issues/events{/number}",
      "events_url": "https://api.github.com/repos/devias-io/material-kit-react/events",
      "assignees_url": "https://api.github.com/repos/devias-io/material-kit-react/assignees{/user}",
      "branches_url": "https://api.github.com/repos/devias-io/material-kit-react/branches{/branch}",
      "tags_url": "https://api.github.com/repos/devias-io/material-kit-react/tags",
      "blobs_url": "https://api.github.com/repos/devias-io/material-kit-react/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/devias-io/material-kit-react/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/devias-io/material-kit-react/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/devias-io/material-kit-react/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/devias-io/material-kit-react/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/devias-io/material-kit-react/languages",
      "stargazers_url": "https://api.github.com/repos/devias-io/material-kit-react/stargazers",
      "contributors_url": "https://api.github.com/repos/devias-io/material-kit-react/contributors",
      "subscribers_url": "https://api.github.com/repos/devias-io/material-kit-react/subscribers",
      "subscription_url": "https://api.github.com/repos/devias-io/material-kit-react/subscription",
      "commits_url": "https://api.github.com/repos/devias-io/material-kit-react/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/devias-io/material-kit-react/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/devias-io/material-kit-react/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/devias-io/material-kit-react/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/devias-io/material-kit-react/contents/{+path}",
      "compare_url": "https://api.github.com/repos/devias-io/material-kit-react/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/devias-io/material-kit-react/merges",
      "archive_url": "https://api.github.com/repos/devias-io/material-kit-react/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/devias-io/material-kit-react/downloads",
      "issues_url": "https://api.github.com/repos/devias-io/material-kit-react/issues{/number}",
      "pulls_url": "https://api.github.com/repos/devias-io/material-kit-react/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/devias-io/material-kit-react/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/devias-io/material-kit-react/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/devias-io/material-kit-react/labels{/name}",
      "releases_url": "https://api.github.com/repos/devias-io/material-kit-react/releases{/id}",
      "deployments_url": "https://api.github.com/repos/devias-io/material-kit-react/deployments",
      "created_at": "2019-05-02T15:25:39Z",
      "updated_at": "2021-12-19T01:57:56Z",
      "pushed_at": "2021-12-09T01:15:45Z",
      "git_url": "git://github.com/devias-io/material-kit-react.git",
      "ssh_url": "git@github.com:devias-io/material-kit-react.git",
      "clone_url": "https://github.com/devias-io/material-kit-react.git",
      "svn_url": "https://github.com/devias-io/material-kit-react",
      "homepage": "http://material-kit-react.devias.io",
      "size": 5070,
      "stargazers_count": 3464,
      "watchers_count": 3464,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 1371,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 6,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [
        "admin",
        "admin-dashboard",
        "admin-template",
        "auth0",
        "authentication",
        "dark-theme",
        "dashboard",
        "devias",
        "firebase",
        "firebase-auth",
        "material-dashboard",
        "material-theme",
        "mui",
        "nextjs",
        "nodejs",
        "react",
        "reactjs",
        "tailwind",
        "typescript"
      ],
      "visibility": "public",
      "forks": 1371,
      "open_issues": 6,
      "watchers": 3464,
      "default_branch": "main",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "score": 1.0
    },
    {
      "id": 291805291,
      "node_id": "MDEwOlJlcG9zaXRvcnkyOTE4MDUyOTE=",
      "name": "jetstream",
      "full_name": "laravel/jetstream",
      "private": false,
      "owner": {
        "login": "laravel",
        "id": 958072,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjk1ODA3Mg==",
        "avatar_url": "https://avatars.githubusercontent.com/u/958072?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/laravel",
        "html_url": "https://github.com/laravel",
        "followers_url": "https://api.github.com/users/laravel/followers",
        "following_url": "https://api.github.com/users/laravel/following{/other_user}",
        "gists_url": "https://api.github.com/users/laravel/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/laravel/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/laravel/subscriptions",
        "organizations_url": "https://api.github.com/users/laravel/orgs",
        "repos_url": "https://api.github.com/users/laravel/repos",
        "events_url": "https://api.github.com/users/laravel/events{/privacy}",
        "received_events_url": "https://api.github.com/users/laravel/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "html_url": "https://github.com/laravel/jetstream",
      "description": "Tailwind scaffolding for the Laravel framework.",
      "fork": false,
      "url": "https://api.github.com/repos/laravel/jetstream",
      "forks_url": "https://api.github.com/repos/laravel/jetstream/forks",
      "keys_url": "https://api.github.com/repos/laravel/jetstream/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/laravel/jetstream/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/laravel/jetstream/teams",
      "hooks_url": "https://api.github.com/repos/laravel/jetstream/hooks",
      "issue_events_url": "https://api.github.com/repos/laravel/jetstream/issues/events{/number}",
      "events_url": "https://api.github.com/repos/laravel/jetstream/events",
      "assignees_url": "https://api.github.com/repos/laravel/jetstream/assignees{/user}",
      "branches_url": "https://api.github.com/repos/laravel/jetstream/branches{/branch}",
      "tags_url": "https://api.github.com/repos/laravel/jetstream/tags",
      "blobs_url": "https://api.github.com/repos/laravel/jetstream/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/laravel/jetstream/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/laravel/jetstream/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/laravel/jetstream/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/laravel/jetstream/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/laravel/jetstream/languages",
      "stargazers_url": "https://api.github.com/repos/laravel/jetstream/stargazers",
      "contributors_url": "https://api.github.com/repos/laravel/jetstream/contributors",
      "subscribers_url": "https://api.github.com/repos/laravel/jetstream/subscribers",
      "subscription_url": "https://api.github.com/repos/laravel/jetstream/subscription",
      "commits_url": "https://api.github.com/repos/laravel/jetstream/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/laravel/jetstream/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/laravel/jetstream/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/laravel/jetstream/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/laravel/jetstream/contents/{+path}",
      "compare_url": "https://api.github.com/repos/laravel/jetstream/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/laravel/jetstream/merges",
      "archive_url": "https://api.github.com/repos/laravel/jetstream/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/laravel/jetstream/downloads",
      "issues_url": "https://api.github.com/repos/laravel/jetstream/issues{/number}",
      "pulls_url": "https://api.github.com/repos/laravel/jetstream/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/laravel/jetstream/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/laravel/jetstream/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/laravel/jetstream/labels{/name}",
      "releases_url": "https://api.github.com/repos/laravel/jetstream/releases{/id}",
      "deployments_url": "https://api.github.com/repos/laravel/jetstream/deployments",
      "created_at": "2020-08-31T19:25:24Z",
      "updated_at": "2021-12-18T15:55:20Z",
      "pushed_at": "2021-12-17T15:18:09Z",
      "git_url": "git://github.com/laravel/jetstream.git",
      "ssh_url": "git@github.com:laravel/jetstream.git",
      "clone_url": "https://github.com/laravel/jetstream.git",
      "svn_url": "https://github.com/laravel/jetstream",
      "homepage": "https://jetstream.laravel.com",
      "size": 1522,
      "stargazers_count": 3101,
      "watchers_count": 3101,
      "language": "PHP",
      "has_issues": true,
      "has_projects": false,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": false,
      "forks_count": 574,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 1,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [
        "auth",
        "laravel",
        "tailwind"
      ],
      "visibility": "public",
      "forks": 574,
      "open_issues": 1,
      "watchers": 3101,
      "default_branch": "2.x",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "score": 1.0
    },
    {
      "id": 162028712,
      "node_id": "MDEwOlJlcG9zaXRvcnkxNjIwMjg3MTI=",
      "name": "leerob.io",
      "full_name": "leerob/leerob.io",
      "private": false,
      "owner": {
        "login": "leerob",
        "id": 9113740,
        "node_id": "MDQ6VXNlcjkxMTM3NDA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/9113740?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/leerob",
        "html_url": "https://github.com/leerob",
        "followers_url": "https://api.github.com/users/leerob/followers",
        "following_url": "https://api.github.com/users/leerob/following{/other_user}",
        "gists_url": "https://api.github.com/users/leerob/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/leerob/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/leerob/subscriptions",
        "organizations_url": "https://api.github.com/users/leerob/orgs",
        "repos_url": "https://api.github.com/users/leerob/repos",
        "events_url": "https://api.github.com/users/leerob/events{/privacy}",
        "received_events_url": "https://api.github.com/users/leerob/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/leerob/leerob.io",
      "description": "✨  My portfolio built with Next.js, Tailwind, Prisma, and Vercel.",
      "fork": false,
      "url": "https://api.github.com/repos/leerob/leerob.io",
      "forks_url": "https://api.github.com/repos/leerob/leerob.io/forks",
      "keys_url": "https://api.github.com/repos/leerob/leerob.io/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/leerob/leerob.io/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/leerob/leerob.io/teams",
      "hooks_url": "https://api.github.com/repos/leerob/leerob.io/hooks",
      "issue_events_url": "https://api.github.com/repos/leerob/leerob.io/issues/events{/number}",
      "events_url": "https://api.github.com/repos/leerob/leerob.io/events",
      "assignees_url": "https://api.github.com/repos/leerob/leerob.io/assignees{/user}",
      "branches_url": "https://api.github.com/repos/leerob/leerob.io/branches{/branch}",
      "tags_url": "https://api.github.com/repos/leerob/leerob.io/tags",
      "blobs_url": "https://api.github.com/repos/leerob/leerob.io/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/leerob/leerob.io/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/leerob/leerob.io/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/leerob/leerob.io/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/leerob/leerob.io/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/leerob/leerob.io/languages",
      "stargazers_url": "https://api.github.com/repos/leerob/leerob.io/stargazers",
      "contributors_url": "https://api.github.com/repos/leerob/leerob.io/contributors",
      "subscribers_url": "https://api.github.com/repos/leerob/leerob.io/subscribers",
      "subscription_url": "https://api.github.com/repos/leerob/leerob.io/subscription",
      "commits_url": "https://api.github.com/repos/leerob/leerob.io/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/leerob/leerob.io/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/leerob/leerob.io/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/leerob/leerob.io/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/leerob/leerob.io/contents/{+path}",
      "compare_url": "https://api.github.com/repos/leerob/leerob.io/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/leerob/leerob.io/merges",
      "archive_url": "https://api.github.com/repos/leerob/leerob.io/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/leerob/leerob.io/downloads",
      "issues_url": "https://api.github.com/repos/leerob/leerob.io/issues{/number}",
      "pulls_url": "https://api.github.com/repos/leerob/leerob.io/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/leerob/leerob.io/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/leerob/leerob.io/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/leerob/leerob.io/labels{/name}",
      "releases_url": "https://api.github.com/repos/leerob/leerob.io/releases{/id}",
      "deployments_url": "https://api.github.com/repos/leerob/leerob.io/deployments",
      "created_at": "2018-12-16T18:22:37Z",
      "updated_at": "2021-12-19T06:01:55Z",
      "pushed_at": "2021-12-16T21:52:03Z",
      "git_url": "git://github.com/leerob/leerob.io.git",
      "ssh_url": "git@github.com:leerob/leerob.io.git",
      "clone_url": "https://github.com/leerob/leerob.io.git",
      "svn_url": "https://github.com/leerob/leerob.io",
      "homepage": "https://leerob.io",
      "size": 144737,
      "stargazers_count": 2821,
      "watchers_count": 2821,
      "language": "TypeScript",
      "has_issues": true,
      "has_projects": false,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": false,
      "forks_count": 568,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 7,
      "license": {
        "key": "other",
        "name": "Other",
        "spdx_id": "NOASSERTION",
        "url": null,
        "node_id": "MDc6TGljZW5zZTA="
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [
        "blog",
        "mdx",
        "nextjs",
        "planetscale",
        "portfolio",
        "prisma",
        "react",
        "tailwindcss",
        "vercel"
      ],
      "visibility": "public",
      "forks": 568,
      "open_issues": 7,
      "watchers": 2821,
      "default_branch": "main",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "score": 1.0
    },
    {
      "id": 245817315,
      "node_id": "MDEwOlJlcG9zaXRvcnkyNDU4MTczMTU=",
      "name": "tailwind-rn",
      "full_name": "vadimdemedes/tailwind-rn",
      "private": false,
      "owner": {
        "login": "vadimdemedes",
        "id": 697676,
        "node_id": "MDQ6VXNlcjY5NzY3Ng==",
        "avatar_url": "https://avatars.githubusercontent.com/u/697676?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/vadimdemedes",
        "html_url": "https://github.com/vadimdemedes",
        "followers_url": "https://api.github.com/users/vadimdemedes/followers",
        "following_url": "https://api.github.com/users/vadimdemedes/following{/other_user}",
        "gists_url": "https://api.github.com/users/vadimdemedes/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/vadimdemedes/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/vadimdemedes/subscriptions",
        "organizations_url": "https://api.github.com/users/vadimdemedes/orgs",
        "repos_url": "https://api.github.com/users/vadimdemedes/repos",
        "events_url": "https://api.github.com/users/vadimdemedes/events{/privacy}",
        "received_events_url": "https://api.github.com/users/vadimdemedes/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/vadimdemedes/tailwind-rn",
      "description": "🦎 Use Tailwind CSS in React Native projects",
      "fork": false,
      "url": "https://api.github.com/repos/vadimdemedes/tailwind-rn",
      "forks_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/forks",
      "keys_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/teams",
      "hooks_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/hooks",
      "issue_events_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/issues/events{/number}",
      "events_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/events",
      "assignees_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/assignees{/user}",
      "branches_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/branches{/branch}",
      "tags_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/tags",
      "blobs_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/languages",
      "stargazers_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/stargazers",
      "contributors_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/contributors",
      "subscribers_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/subscribers",
      "subscription_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/subscription",
      "commits_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/contents/{+path}",
      "compare_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/merges",
      "archive_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/downloads",
      "issues_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/issues{/number}",
      "pulls_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/labels{/name}",
      "releases_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/releases{/id}",
      "deployments_url": "https://api.github.com/repos/vadimdemedes/tailwind-rn/deployments",
      "created_at": "2020-03-08T13:14:48Z",
      "updated_at": "2021-12-19T05:23:59Z",
      "pushed_at": "2021-12-17T21:28:14Z",
      "git_url": "git://github.com/vadimdemedes/tailwind-rn.git",
      "ssh_url": "git@github.com:vadimdemedes/tailwind-rn.git",
      "clone_url": "https://github.com/vadimdemedes/tailwind-rn.git",
      "svn_url": "https://github.com/vadimdemedes/tailwind-rn",
      "homepage": "",
      "size": 692,
      "stargazers_count": 2727,
      "watchers_count": 2727,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 122,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 35,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [

      ],
      "visibility": "public",
      "forks": 122,
      "open_issues": 35,
      "watchers": 2727,
      "default_branch": "master",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "score": 1.0
    },
    {
      "id": 219020626,
      "node_id": "MDEwOlJlcG9zaXRvcnkyMTkwMjA2MjY=",
      "name": "tailwindcss-typography",
      "full_name": "tailwindlabs/tailwindcss-typography",
      "private": false,
      "owner": {
        "login": "tailwindlabs",
        "id": 67109815,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjY3MTA5ODE1",
        "avatar_url": "https://avatars.githubusercontent.com/u/67109815?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tailwindlabs",
        "html_url": "https://github.com/tailwindlabs",
        "followers_url": "https://api.github.com/users/tailwindlabs/followers",
        "following_url": "https://api.github.com/users/tailwindlabs/following{/other_user}",
        "gists_url": "https://api.github.com/users/tailwindlabs/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tailwindlabs/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tailwindlabs/subscriptions",
        "organizations_url": "https://api.github.com/users/tailwindlabs/orgs",
        "repos_url": "https://api.github.com/users/tailwindlabs/repos",
        "events_url": "https://api.github.com/users/tailwindlabs/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tailwindlabs/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "html_url": "https://github.com/tailwindlabs/tailwindcss-typography",
      "description": null,
      "fork": false,
      "url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography",
      "forks_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/forks",
      "keys_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/teams",
      "hooks_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/hooks",
      "issue_events_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/issues/events{/number}",
      "events_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/events",
      "assignees_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/assignees{/user}",
      "branches_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/branches{/branch}",
      "tags_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/tags",
      "blobs_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/languages",
      "stargazers_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/stargazers",
      "contributors_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/contributors",
      "subscribers_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/subscribers",
      "subscription_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/subscription",
      "commits_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/contents/{+path}",
      "compare_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/merges",
      "archive_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/downloads",
      "issues_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/issues{/number}",
      "pulls_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/labels{/name}",
      "releases_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/releases{/id}",
      "deployments_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-typography/deployments",
      "created_at": "2019-11-01T16:16:59Z",
      "updated_at": "2021-12-18T23:32:59Z",
      "pushed_at": "2021-12-17T20:35:05Z",
      "git_url": "git://github.com/tailwindlabs/tailwindcss-typography.git",
      "ssh_url": "git@github.com:tailwindlabs/tailwindcss-typography.git",
      "clone_url": "https://github.com/tailwindlabs/tailwindcss-typography.git",
      "svn_url": "https://github.com/tailwindlabs/tailwindcss-typography",
      "homepage": "tailwindcss-typography.vercel.app",
      "size": 5423,
      "stargazers_count": 2588,
      "watchers_count": 2588,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 167,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 30,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [

      ],
      "visibility": "public",
      "forks": 167,
      "open_issues": 30,
      "watchers": 2588,
      "default_branch": "master",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "score": 1.0
    },
    {
      "id": 362711256,
      "node_id": "MDEwOlJlcG9zaXRvcnkzNjI3MTEyNTY=",
      "name": "playground-macos",
      "full_name": "Renovamen/playground-macos",
      "private": false,
      "owner": {
        "login": "Renovamen",
        "id": 29454156,
        "node_id": "MDQ6VXNlcjI5NDU0MTU2",
        "avatar_url": "https://avatars.githubusercontent.com/u/29454156?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Renovamen",
        "html_url": "https://github.com/Renovamen",
        "followers_url": "https://api.github.com/users/Renovamen/followers",
        "following_url": "https://api.github.com/users/Renovamen/following{/other_user}",
        "gists_url": "https://api.github.com/users/Renovamen/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Renovamen/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Renovamen/subscriptions",
        "organizations_url": "https://api.github.com/users/Renovamen/orgs",
        "repos_url": "https://api.github.com/users/Renovamen/repos",
        "events_url": "https://api.github.com/users/Renovamen/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Renovamen/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/Renovamen/playground-macos",
      "description": "My portfolio website simulating macOS's GUI, developed with React and Tailwind CSS.",
      "fork": false,
      "url": "https://api.github.com/repos/Renovamen/playground-macos",
      "forks_url": "https://api.github.com/repos/Renovamen/playground-macos/forks",
      "keys_url": "https://api.github.com/repos/Renovamen/playground-macos/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/Renovamen/playground-macos/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/Renovamen/playground-macos/teams",
      "hooks_url": "https://api.github.com/repos/Renovamen/playground-macos/hooks",
      "issue_events_url": "https://api.github.com/repos/Renovamen/playground-macos/issues/events{/number}",
      "events_url": "https://api.github.com/repos/Renovamen/playground-macos/events",
      "assignees_url": "https://api.github.com/repos/Renovamen/playground-macos/assignees{/user}",
      "branches_url": "https://api.github.com/repos/Renovamen/playground-macos/branches{/branch}",
      "tags_url": "https://api.github.com/repos/Renovamen/playground-macos/tags",
      "blobs_url": "https://api.github.com/repos/Renovamen/playground-macos/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/Renovamen/playground-macos/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/Renovamen/playground-macos/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/Renovamen/playground-macos/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/Renovamen/playground-macos/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/Renovamen/playground-macos/languages",
      "stargazers_url": "https://api.github.com/repos/Renovamen/playground-macos/stargazers",
      "contributors_url": "https://api.github.com/repos/Renovamen/playground-macos/contributors",
      "subscribers_url": "https://api.github.com/repos/Renovamen/playground-macos/subscribers",
      "subscription_url": "https://api.github.com/repos/Renovamen/playground-macos/subscription",
      "commits_url": "https://api.github.com/repos/Renovamen/playground-macos/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/Renovamen/playground-macos/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/Renovamen/playground-macos/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/Renovamen/playground-macos/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/Renovamen/playground-macos/contents/{+path}",
      "compare_url": "https://api.github.com/repos/Renovamen/playground-macos/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/Renovamen/playground-macos/merges",
      "archive_url": "https://api.github.com/repos/Renovamen/playground-macos/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/Renovamen/playground-macos/downloads",
      "issues_url": "https://api.github.com/repos/Renovamen/playground-macos/issues{/number}",
      "pulls_url": "https://api.github.com/repos/Renovamen/playground-macos/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/Renovamen/playground-macos/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/Renovamen/playground-macos/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/Renovamen/playground-macos/labels{/name}",
      "releases_url": "https://api.github.com/repos/Renovamen/playground-macos/releases{/id}",
      "deployments_url": "https://api.github.com/repos/Renovamen/playground-macos/deployments",
      "created_at": "2021-04-29T06:20:32Z",
      "updated_at": "2021-12-18T21:08:33Z",
      "pushed_at": "2021-12-15T05:05:08Z",
      "git_url": "git://github.com/Renovamen/playground-macos.git",
      "ssh_url": "git@github.com:Renovamen/playground-macos.git",
      "clone_url": "https://github.com/Renovamen/playground-macos.git",
      "svn_url": "https://github.com/Renovamen/playground-macos",
      "homepage": "https://portfolio.zxh.io",
      "size": 68998,
      "stargazers_count": 2461,
      "watchers_count": 2461,
      "language": "TypeScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": true,
      "forks_count": 196,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 1,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [
        "react",
        "redux",
        "tailwindcss",
        "typescript"
      ],
      "visibility": "public",
      "forks": 196,
      "open_issues": 1,
      "watchers": 2461,
      "default_branch": "main",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "score": 1.0
    },
    {
      "id": 273585960,
      "node_id": "MDEwOlJlcG9zaXRvcnkyNzM1ODU5NjA=",
      "name": "FigmaToCode",
      "full_name": "bernaferrari/FigmaToCode",
      "private": false,
      "owner": {
        "login": "bernaferrari",
        "id": 351125,
        "node_id": "MDQ6VXNlcjM1MTEyNQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/351125?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/bernaferrari",
        "html_url": "https://github.com/bernaferrari",
        "followers_url": "https://api.github.com/users/bernaferrari/followers",
        "following_url": "https://api.github.com/users/bernaferrari/following{/other_user}",
        "gists_url": "https://api.github.com/users/bernaferrari/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/bernaferrari/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/bernaferrari/subscriptions",
        "organizations_url": "https://api.github.com/users/bernaferrari/orgs",
        "repos_url": "https://api.github.com/users/bernaferrari/repos",
        "events_url": "https://api.github.com/users/bernaferrari/events{/privacy}",
        "received_events_url": "https://api.github.com/users/bernaferrari/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bernaferrari/FigmaToCode",
      "description": "Generate responsive pages and apps on HTML, Tailwind, Flutter and SwiftUI.",
      "fork": false,
      "url": "https://api.github.com/repos/bernaferrari/FigmaToCode",
      "forks_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/forks",
      "keys_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/teams",
      "hooks_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/hooks",
      "issue_events_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/issues/events{/number}",
      "events_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/events",
      "assignees_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/assignees{/user}",
      "branches_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/branches{/branch}",
      "tags_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/tags",
      "blobs_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/languages",
      "stargazers_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/stargazers",
      "contributors_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/contributors",
      "subscribers_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/subscribers",
      "subscription_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/subscription",
      "commits_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/contents/{+path}",
      "compare_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/merges",
      "archive_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/downloads",
      "issues_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/issues{/number}",
      "pulls_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/labels{/name}",
      "releases_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/releases{/id}",
      "deployments_url": "https://api.github.com/repos/bernaferrari/FigmaToCode/deployments",
      "created_at": "2020-06-19T21:02:32Z",
      "updated_at": "2021-12-18T10:15:20Z",
      "pushed_at": "2021-09-22T00:38:30Z",
      "git_url": "git://github.com/bernaferrari/FigmaToCode.git",
      "ssh_url": "git@github.com:bernaferrari/FigmaToCode.git",
      "clone_url": "https://github.com/bernaferrari/FigmaToCode.git",
      "svn_url": "https://github.com/bernaferrari/FigmaToCode",
      "homepage": "https://www.figma.com/community/plugin/842128343887142055",
      "size": 14027,
      "stargazers_count": 2300,
      "watchers_count": 2300,
      "language": "TypeScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 97,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 22,
      "license": {
        "key": "gpl-3.0",
        "name": "GNU General Public License v3.0",
        "spdx_id": "GPL-3.0",
        "url": "https://api.github.com/licenses/gpl-3.0",
        "node_id": "MDc6TGljZW5zZTk="
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [
        "conversion",
        "figma",
        "figma-plugins",
        "flutter",
        "html",
        "responsive",
        "svelte",
        "swift",
        "swiftui",
        "tailwind",
        "tailwindcss",
        "typescript"
      ],
      "visibility": "public",
      "forks": 97,
      "open_issues": 22,
      "watchers": 2300,
      "default_branch": "master",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "score": 1.0
    },
    {
      "id": 343011579,
      "node_id": "MDEwOlJlcG9zaXRvcnkzNDMwMTE1Nzk=",
      "name": "tailwindcss-jit",
      "full_name": "tailwindlabs/tailwindcss-jit",
      "private": false,
      "owner": {
        "login": "tailwindlabs",
        "id": 67109815,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjY3MTA5ODE1",
        "avatar_url": "https://avatars.githubusercontent.com/u/67109815?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tailwindlabs",
        "html_url": "https://github.com/tailwindlabs",
        "followers_url": "https://api.github.com/users/tailwindlabs/followers",
        "following_url": "https://api.github.com/users/tailwindlabs/following{/other_user}",
        "gists_url": "https://api.github.com/users/tailwindlabs/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tailwindlabs/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tailwindlabs/subscriptions",
        "organizations_url": "https://api.github.com/users/tailwindlabs/orgs",
        "repos_url": "https://api.github.com/users/tailwindlabs/repos",
        "events_url": "https://api.github.com/users/tailwindlabs/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tailwindlabs/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "html_url": "https://github.com/tailwindlabs/tailwindcss-jit",
      "description": null,
      "fork": false,
      "url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit",
      "forks_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/forks",
      "keys_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/teams",
      "hooks_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/hooks",
      "issue_events_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/issues/events{/number}",
      "events_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/events",
      "assignees_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/assignees{/user}",
      "branches_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/branches{/branch}",
      "tags_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/tags",
      "blobs_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/languages",
      "stargazers_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/stargazers",
      "contributors_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/contributors",
      "subscribers_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/subscribers",
      "subscription_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/subscription",
      "commits_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/contents/{+path}",
      "compare_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/merges",
      "archive_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/downloads",
      "issues_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/issues{/number}",
      "pulls_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/labels{/name}",
      "releases_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/releases{/id}",
      "deployments_url": "https://api.github.com/repos/tailwindlabs/tailwindcss-jit/deployments",
      "created_at": "2021-02-28T03:26:09Z",
      "updated_at": "2021-12-18T12:37:13Z",
      "pushed_at": "2021-04-05T19:46:16Z",
      "git_url": "git://github.com/tailwindlabs/tailwindcss-jit.git",
      "ssh_url": "git@github.com:tailwindlabs/tailwindcss-jit.git",
      "clone_url": "https://github.com/tailwindlabs/tailwindcss-jit.git",
      "svn_url": "https://github.com/tailwindlabs/tailwindcss-jit",
      "homepage": "",
      "size": 697,
      "stargazers_count": 2260,
      "watchers_count": 2260,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": false,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 34,
      "mirror_url": null,
      "archived": true,
      "disabled": false,
      "open_issues_count": 4,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "topics": [

      ],
      "visibility": "public",
      "forks": 34,
      "open_issues": 4,
      "watchers": 2260,
      "default_branch": "main",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "score": 1.0
    }
  ]
}
export default result;
