name: Build and Deploy to Netlify

on:
  push:
    branches:
      - feature/set-github-token

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Setup environment variables
        run: |
          sed -i "s#REACT_APP_GITHUB_TOKEN_VALUE#${{ secrets.REACT_APP_GITHUB_TOKEN }}#g" .env-production
          cp .env-production .env
          cat .env
      - name: Run Unit Test
        run: yarn run test:no-watch
      - name: Run Build
        run: yarn run build
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build --prodIfUnlocked
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

